"use client";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/navbar/Navbar";
import NavbarBottom from "./components/navbar/NavbarBottom";
import { usePathname } from "next/navigation";
import { useThemeStore } from "./store/themeStore";

// hindi nagana metadata pag may use client
// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const pathname = usePathname();
    const hideComponents = pathname === "/login" || pathname === "/register";

    const { isDarked } = useThemeStore();
    const mainBg = isDarked
        ? "bg-[#1A1F40] text-[#f5f5f5]"
        : "bg-[#DAE0E6] text-black";

    return (
        <html lang="en">
            <head>
                <title>Social App</title>
            </head>
            <body>
                <ChakraProvider>
                    <div className={`${mainBg} relative w-full flex flex-col `}>
                        {!hideComponents && <Navbar />}
                        {children}
                        {!hideComponents && <NavbarBottom />}
                    </div>
                </ChakraProvider>
            </body>
        </html>
    );
}
