"use client";

import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/navbar/Navbar";
import NavbarBottom from "./components/navbar/NavbarBottom";
import { useThemeStore } from "./store/themeStore";

// hindi nagana metadata pag may use client
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// whitebg = #e9ecef

export default function RootLayout({ children }) {
    const { isDarked } = useThemeStore();
    const darkMode = isDarked
        ? "bg-[#1A1F40] text-[#f5f5f5]"
        : "bg-[#e9ecef] text-black";

    return (
        <html lang="en">
            <body>
                <ChakraProvider>
                    <div
                        className={`${darkMode} relative w-full flex flex-col`}
                    >
                        <Navbar />
                        {children}
                        <NavbarBottom />
                    </div>
                </ChakraProvider>
            </body>
        </html>
    );
}
