"use client";

import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/navbar/Navbar";
import NavbarBottom from "./components/navbar/NavbarBottom";
import { useThemeStore } from "./store/themeStore";
import { usePathname } from "next/navigation";
import Head from "next/head";

// hindi nagana metadata pag may use client
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const pathname = usePathname();
    const hideComponents = pathname === "/login" || pathname === "/register";

    const { isDarked } = useThemeStore();
    const darkMode = isDarked
        ? "bg-[#1A1F40] text-[#f5f5f5]"
        : "bg-[#e9ecef] text-black";

    return (
        <html lang="en">
            <head>
                <meta charSet="utf-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <title>Social App</title>
                {/* <link rel="icon" href="" /> */}
            </head>
            <body>
                <ChakraProvider>
                    <div
                        className={`${darkMode} relative w-full flex flex-col `}
                    >
                        {!hideComponents && <Navbar />}
                        {children}
                        {!hideComponents && <NavbarBottom />}
                    </div>
                </ChakraProvider>
            </body>
        </html>
    );
}
